language: node_js
node_js:
    - 12
cache:
    directories:
        - node_modules
before_script:
    - 'curl -H "Cache-Control: no-cache" https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash'
script:
    - npm install -g codecov
    - yarn
    - yarn lint
    - yarn test:ci
    - yarn build
    - fossa init
    - fossa analyze
    - yarn test --coverage
    - codecov
after_success:
    - fossa test
